# Generated by Django 2.2 on 2019-08-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='add some detail')),
                ('availability', models.BooleanField()),
                ('condition', models.CharField(max_length=200)),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hidden', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingLibrary.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingLibrary.User')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingLibrary.CheckoutStatus')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingLibrary.UserItem')),
            ],
        ),
        migrations.AddField(
            model_name='useritem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingLibrary.UserItemCategory'),
        ),
    ]
