# Generated by Django 2.2.4 on 2019-08-15 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
                ('replacement_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('request_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
                ('checkout_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lendingLibrary.CheckoutStatus')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_history', to='lendingLibrary.UserItem')),
            ],
        ),
        migrations.AddField(
            model_name='useritem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lendingLibrary.UserItemCategory'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lendingLibrary.UserItemCondition'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lendingLibrary.UserItemStatus'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
