# Generated by Django 2.2 on 2019-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingLibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='useritem',
            name='image_url',
            field=models.CharField(default='https://lar-mo.com/images/lazy_placeholder.gif', max_length=200),
        ),
    ]
