# Generated by Django 2.2 on 2019-08-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendingLibrary', '0002_auto_20190806_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCondition',
            new_name='UserItemCondition',
        ),
    ]
