# Generated by Django 2.2 on 2019-08-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendingLibrary', '0003_auto_20190806_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendingLibrary.UserItemCondition'),
        ),
    ]
