# Generated by Django 2.2 on 2019-08-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendingLibrary', '0004_auto_20190806_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='availability',
            new_name='available',
        ),
    ]
