# Generated by Django 2.2 on 2019-08-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendingLibrary', '0005_auto_20190806_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='available',
            new_name='checked_out',
        ),
    ]
